name: merge-request
on:
  pull_request:
    branches: [ staging ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Install packages
        run: yarn
      - name: Run prettier
        run: yarn check:prettier
      - name: Run linter
        run: yarn check:lint
      - name: Run type check
        run: yarn check:type
      - name: Test build
        env:
          NEXT_PUBLIC_GA_TRACKING_ID: ${{ secrets.NEXT_PUBLIC_GA_TRACKING_ID }}
          NEXT_PUBLIC_EMAIL_USER_ID: ${{ secrets.NEXT_PUBLIC_EMAIL_USER_ID }}
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
        run: yarn build
